piryopt/pienryhmien-optimointi

src/algorithms/hungarian.py
src/algorithms/weights.py
src/routes.py
src/templates/results.html
tests/hungarian_test.py
tests/resource.robot
tests/ui_testing.robot
tests/weights_test.py

Changes
- Weights class now always generates one extra weight for options outside of student choices with key -1
- Removed runtime measuring from Hungarian and removed reporting of runtime from UI
- Hungarian refactored, but apart from runtime reporting works like it did before
- Added two output get commands to Hungarian
- Added tests for Hungarian
- Pylint checked for Weights and Hungarian and fixed some errors

Refactor weights and hungarian, add tests

---

.github/workflows/staging.yml
schema.sql
src/algorithms/hungarian.py
src/repositories/survey_repository.py
src/routes.py
src/services/survey_service.py
src/services/survey_tools.py
src/static/css/style.css
src/templates/closedsurvey.html
src/templates/results.html
src/templates/survey_answers.html
src/templates/surveys.html
src/tools/rankings_converter.py
src/tools/survey_result_helper.py
tests/survey_repository_test.py

Uudet ominaisuudet:
- Kun käyttäjä on sulkenut kyselyn, hän voi luoda ryhmityksen ja tallentaa tulokset tietokantaan.
- Pari bugi fixiä
- surveys tauluun result_saved
- Routesin funktioihin dokumentaatiota/infoa
- lisädataa opettajille kyselyistä (onko ryhmitelty, monesko valinta)

Save results

---

src/routes.py
src/static/js/create_survey.js
src/templates/create_survey.html

Response messages are shown based on what is returned from the backend. However currently most exceptions are catched in the backed so to make them appear correctly changes need to be made to repositories

Response messages from server on survey creation

---

src/templates/surveys.html

Added copy link in surveys listing

Added copy link in surveys listing

---

src/repositories/survey_repository.py
src/routes.py
src/services/final_group_service.py
src/services/survey_choices_service.py
src/services/survey_service.py
src/services/user_rankings_service.py
src/services/user_service.py
src/static/css/dark.css
src/templates/index.html
src/templates/survey.html
src/templates/surveys.html
tests/survey_repository_test.py
tests/survey_service_test.py

- Minor UI edit
- removed console prints
- added jsonify responses
- Students and teachers have different operations and views available to them
- Tests for new functions

Student teacher access + error messages

---

schema.sql
src/repositories/survey_repository.py
src/routes.py
src/tools/db_tools.py
tests/survey_choices_repository_test.py
tests/survey_choices_service_test.py
tests/survey_repository_test.py
tests/survey_service_test.py

Survey ID changed to a 10 character long varchar consisting of randomly generated set of characters in 0-9a-zA-Z. Note: requires schema change

Unique survey

---

src/routes.py
src/templates/survey_answers.html

Added button 'Poista tämä vastaus' in survey_answers.html.

Added button for removing a survey input in answers list

---

src/routes.py
src/templates/survey_answers.html

Fixed:
- routes.py path
- button style
- deleted unneccesary hidden input

Delete individual answer: Style and logic fixes

---

.github/workflows/main.yml
.github/workflows/staging.yml
src/routes.py
src/templates/base.html
src/templates/mock_ad.html
src/tools/db_data_gen.py
tests/staging_testing.robot
tests/survey_testing.robot

Implement logging out and add tests

Remove student number

---

src/repositories/survey_repository.py
src/routes.py
src/services/survey_service.py
src/templates/survey.html

The amount of minimum choices needed visible in answer form.

Min choices visible in form

---

src/algorithms/hungarian.py
src/routes.py
src/services/survey_choices_service.py
src/templates/survey_answers.html
tests/survey_choices_service_test.py

- Created method to add a non-group that has name "Tyhjä"
- if more answers than spaces a non-group is created with an equal number of spots to the extra students
- Added a test for creating non-group

If more answers than spaces, extra students are put in non-group

---

tests/user_service_test.py

Few unittests for user_service.py to improve the project test coverage.

More unittests

---

.github/workflows/staging.yml
src/routes.py
src/services/user_service.py
src/templates/base.html

- Fixed a bug where the user would always be redirected to the front page after logging in
- Fixed a bug where session data wasn't working properly

Staging bugs

---

src/templates/survey_answers.html

Link before edit:
Link button after edit:

Make "back to surveys list" link into a button

---

src/tools/survey_result_helper.py

- Fixes bug where rejections list wasn't handled correctly in group assignment and application crashed

Fix error in handling rejections list

---

.coveragerc
src/algorithms/hungarian.py
tests/hungarian_test.py

- If student is place outside of their preference list, their happiness is number of choices +1
- Test this case

Update student happiness calculation and add test

---

src/repositories/user_repository.py
src/routes.py
src/services/feedback_service.py
src/services/survey_service.py
src/services/user_service.py
src/templates/admintools/admin_analytics.html
src/templates/admintools/admin_closed_feedback.html
src/templates/base.html
src/tools/date_converter.py

- Fixed csrf bugs
- Analytics changes
- Added page for closed feedback
- Functions for opening surveys

Csrf stuff + prev pr

---

src/routes.py
src/services/survey_choices_service.py

- Fixed minmax bugs caused by lazy coding

minmax bug fixes

---

src/routes.py
src/tools/survey_result_helper.py

- Fixed a crash which happened when min_size algo removed a group which resulted in not enough total seats for students
- Instead of removing the group with the least amount of people in it, remove the group that has the lowest user ranking

Min size improvements

---

src/static/css/dark.css
src/templates/index.html

Removed tervetuloa, changed the table to a grid and slightly softened the edges of list elements

Minor changes to the front page

---

src/routes.py
src/templates/surveys.html
src/tools/survey_result_helper.py

- Minor visual updates to indicate that the results of the survey have been changed. 
- Refactored survey_results

Survey results refactor

---

src/routes.py

Fixed a bug where anyone could copy a survey, as long as they had the id. Now only owners can copy their survey

Limit who can copy a survey

---

.github/workflows/main.yml
Dockerfile.test
docker-compose.yml
docs-2.0/testing_guide.md
poetry.lock
pyproject.toml
src/requirements.txt
tests/playwright/playwright_tools.py

- Add test service to docker-compose
- Add initial testing guide
- Move playwright to dev dependencies in pyproject.toml
- Add check if playwright is ran through localhost or in a container

Add local testing through Docker

---

src/static/css/create_survey.css
src/static/js/create_survey.js
src/templates/create_survey.html

UI improvements

---

.gitignore
schema.sql
tests/playwright/survey_testing.py

- add playwright test
- update schema

Mandatory feature testing

---

tests/test_files/test_survey1.json
tests/test_survey_choices_service.py
tests/test_survey_service.py
tests/test_user_repository.py
tests/test_user_service.py

Add tests for user service, survey service, survey choice service and user repository to improve test coverage.

 Improve test coverage
